---
    deployment:
        tasks:
        - export DEPLOYPATH=/home/u1545300/public_html/
        -/bin/cp index.html $DEPLOYPATH
        -/bin/cp -R assets $DEPLOYPATH
        -/bin/cp -R css $DEPLOYPATH
        -/bin/cp -R js $DEPLOYPATH

